# Generated by Django 3.2.6 on 2021-08-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('audiobooks', 'audiobooks'), ('readables', 'readables')], default='readables', max_length=255),
        ),
    ]
